### ISSUE TITLE
Feature Request: Dequeue or Open

### ISSUE THREAD

**Issue by efaden** [drmibell/node-red-contrib-queue-gate#25]
Looking for a way to only allow a single flow through my code.  Was planning to use queue/open, but the issue is that when you open it flushes, I'm looking for a way to dequeue if there is a queue or open if their isn't within a single action.  Is that possible?

**Comment by drmibell** [comment]
If you use queue/default, with the default state set to `open`, the queue will be reset (deleted) rather than flushed.

On the other hand, I agree with the comment by @shrickus on the Forum that what you really need is the capability of the [semaphore nodes](https://flows.nodered.org/node/node-red-contrib-semaphore). I suspect that even with the q-gate node configured as I suggested, you would still need some additional logic to put it back into the the queueing state when necessary.

**Comment by efaden** [comment]
Yeah, without additional logic it didn't work.  The simple queue node did work out for this use.  But I may switch to semaphore.
